"""command book 層：把動作抽象成可組合的指令，並提供攻擊決策。"""
from src.commands.command_book import (
    Command,
    CommandContext,
    CommandBook,
    MoveCommand,
    AttackCommand,
    BuffCommand,
    PotionCommand,
    ChangeChannelCommand,
    ApproachCommand,
    JumpMoveCommand,
    COMMAND_REGISTRY,
)
from src.commands.combat import (
    CombatDecision,
    PlatformState,
    select_nearest,
    dominant_side,
    plan_attack,
    plan_ranged,
    decision_to_actions,
    plan_patrol,
    approach_is_safe,
    filter_attackable,
    on_platform,
    plan_two_platforms,
)

__all__ = [
    "Command",
    "CommandContext",
    "CommandBook",
    "MoveCommand",
    "AttackCommand",
    "BuffCommand",
    "PotionCommand",
    "ChangeChannelCommand",
    "ApproachCommand",
    "JumpMoveCommand",
    "COMMAND_REGISTRY",
    "CombatDecision",
    "PlatformState",
    "select_nearest",
    "dominant_side",
    "plan_attack",
    "plan_ranged",
    "decision_to_actions",
    "plan_patrol",
    "approach_is_safe",
    "filter_attackable",
    "on_platform",
    "plan_two_platforms",
]
